### ISSUE TITLE
SPADE availability for Cytoscape 3

### ISSUE THREAD

**Issue by srikanthBezawada** [nolanlab/spade#118]
Hello,

Is SPADE app available for Cytoscape 3.0 ? I am interested in porting it to support for Cytoscape 3.0 as a **Cytoscape app**

Thanks,
Srikanth.

**Comment by zbjornson** [comment]
We no longer support the plugin for any version of Cytoscape since Cytobank provides a complete interface. We made an attempt in January to support Cytoscape 3.0, but we could not find some of the equivalent APIs. The progress we made is here: https://github.com/nolanlab/cytospade/tree/cytoscape-3. We also started working on a Gephi plugin, https://github.com/nolanlab/cytospade/tree/Gephi.

(Looking at that repository now, I realize the commit history is messed up for the master branch. If you want to work on it, let me know and I'll repair the repository.) Thanks!

**Comment by srikanthBezawada** [comment]
I recently worked on  [SpanningTree app for Cytoscape3](http://apps.cytoscape.org/apps/cyspanningtree), [tiedie app](http://apps.cytoscape.org/apps/tiedie), [adj app](http://apps.cytoscape.org/apps/adjexporter)

I am interested in porting & developing Spade app for Cytoscape3. But I would need someone to mentor me. Let me know.

**Comment by zbjornson** [comment]
Sorry for the delay. We unfortunately don't have a ton of resources to invest in continuing development of the Cytoscape plugin, but if you want to fork the repository I can try to help where I can. Your interest is appreciated!

**Comment by srikanthBezawada** [comment]
I shall get back to you once I can work on the 3.0 version, meanwhile you can repair the repository. Thanks!
